### ISSUE TITLE
Test with python-scikit-learn 1.1.0 is not passing

### ISSUE THREAD

**Issue by carlosal1015** [firefly-cpp/NiaAML#71]
Hi, the following test `conftest.py` is not passing with recent version of sklearn, with versions less than 1.1.0, all the tests are passing.

```python
niaaml/__init__.py:1: in <module>
    from niaaml import classifiers
niaaml/classifiers/__init__.py:2: in <module>
    from niaaml.classifiers.random_forest import RandomForest
niaaml/classifiers/random_forest.py:8: in <module>
    from sklearn.exceptions import (
E   ImportError: cannot import name 'ChangedBehaviorWarning' from 'sklearn.exceptions' (/usr/lib/python3.10/site-packages/sklearn/exceptions.py)
============================================================================== short test summary info ==============================================================================
ERROR  - ImportError: cannot import name 'ChangedBehaviorWarning' from 'sklearn.exceptions' (/usr/lib/python3.10/site-packages/sklearn/exceptions.py)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================= 1 error in 0.70s ==================================================================================
```
Setup:

- [`python 3.10.4`](https://archlinux.org/packages/core/x86_64/python)
- [`pandas 1.4.2`](https://archlinux.org/packages/community/x86_64/python-pandas)
- [`scikit-learn 1.1.0`](https://archlinux.org/packages/community/x86_64/python-scikit-learn)
- [`NiaPy 2.0.1`](https://aur.archlinux.org/packages/python-niapy)
- [`NiaAML 1.1.7`](https://aur.archlinux.org/packages/python-niaaml)

OS: Arch Linux

Steps to reproduce:

For easy setup, can be reproduce with an Arch Linux based with base-devel group and AUR helper.
```console
$ docker run -it --rm registry.gitlab.com/dune-archiso/images/dune-archiso-yay
$ yay -Syu python-niaaml
```

**Comment by firefly-cpp** [comment]
It is also failing on Alpine Linux.

**Comment by firefly-cpp** [comment]
@lukapecnik, please check it out.

**Comment by zStupan** [comment]
ChangedBehaviorWarning and NonBLASDotWarning were deprecated in scikit-learn 0.24.2 and removed in the newest version because they were not being used. They have to be removed from the imports and constructors of every classifier.

**Comment by firefly-cpp** [comment]
@zStupan, can we ask you to propose a PR with suggested changes?

**Comment by firefly-cpp** [comment]
@zStupan, according to the logs, a previous version of the scikit-learn package is installed. The installed version may be the main problem.
