### ISSUE TITLE
First Contribution: minor styling changes in `README.md` 

### ISSUE THREAD

**Issue by LaurenzBeck** [firefly-cpp/NiaAML#83]
Hi there 👋

I'm **Laurenz Farthofer** and I will contribute to this package as part of the HCI course of the TU Graz.

I am creating this uncritical issue to test the whole github contribution workflow.

I plan to add a few stylistic quirks I like to use in my own `README.md`s including:

- [ ] adding a title
- [ ] adding a table of contents with markdown links to the other sections
- [ ] center-align the github badges/shields
- [ ] adding horizontal rules
- [ ] adding emojis to section headings

Some people prefer a more "professional" documentation. I really enjoy colorful technical documents and think it is a really good way to improve the engagement of readers.

I will create a PR for this issues. Feel free to comment on the changes there 😉

**Comment by firefly-cpp** [comment]
Hi Laurenz!

It is nice to have you aboard. Your ideas are welcome, so feel free to submit pull requests.

Currently, the owner of this repository, @lukapecnik, will transfer this repository to me, and then I will add you to contributors so you can easily add labels, merge commits, etc.

I am looking forward to the NiaAML v3. :)
